[workspace]
resolver = "2"

members = [
    "practice_1_hello",
    "practice_1_1_comments",
    "practice_1_2_formatted_print",
    "practice_1_2_1_debug",
    "practice_1_2_2_display",
    "practice_1_2_2_1_list",
    "practice_1_2_3_formatting",
    "practice_2_primitives",
    "practice_2_1_literals",
    "practice_2_2_tuples",
    "practice_2_3_arrays_and_slices",
]
